[package]
name = "day20"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared/" }

[build]
rustflags = ["-C", "target-cpu=native", "link-args=-Wl", "-zstack-size=16194304"]

[profile.release]
codegen-units = 1
lto = "fat"