[package]
name = "day25"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared/" }

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
codegen-units = 1
lto = "fat"